---
title: 'Exporatory analysis of the Ames house price dataset'
output: html_document
---

```{r, message=F, comment=NA}
require(dplyr)
require(ggplot2)
require(tidyr)

train <- read.csv('../data/train.csv')

cat('dimensions: ', dim(train))
head(train)
```

```{r, fig.height=10}
fraction_available <- sapply(train, function(col) 1 - mean(is.na(col)))
available_values <- data.frame(fraction_available)
available_values['variable'] <- row.names(available_values)
available_values['complete'] <- as.factor(available_values$fraction_available == 1)

ggplot(available_values, aes(x=variable, y=fraction_available, fill=complete) ) + 
  geom_bar( stat='identity' ) + 
  coord_flip() + 
  scale_fill_manual(values=c('gray50', 'gray80')) +
  ggtitle('fraction of available (not NA) values') + 
  theme(plot.title=element_text(size=16, hjust=0.5))
```

## Split training set in to validation-set and training set

```{r}
train <- train[, colSums(is.na(train)) == 0]  # remove all columns with NAs


validation_fraction <- 0.2
validation_row_indices <- sample(row.names(train), size=validation_fraction*nrow(train), replace=F)
train_row_indices = row.names(train)[!row.names(train) %in% validation_row_indices]

validation <- train[validation_row_indices, ]
train <- train[train_row_indices, ]
```

```{r}
naive_model <- lm(data=train, SalePrice ~ .)
summary(naive_model)
```

```{r}
#predict(naive_model, newdata=validation)
```



## ignore test set for now
```{r, echo=F, eval=F}
# test <- read.csv('../data/test.csv')
# test_complete <- test[, colSums(is.na(test)) == 0]  # remove all columns with NAs
# 
# # use all variables that are complete in the test set + the target variable (price)
# train_complete <- train[, c(colnames(test_complete), 'SalePrice')]
# 
# naive_model <- lm(data=train_complete, SalePrice ~ .)
# summary(naive_model)
```


